### ISSUE TITLE
blockquote example unclear

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-html-rfc-bis#10]
The example in https://greenbytes.de/tech/webdav/rfc7992.html#rfc.section.9.10 has:

    <cite>&mdash; <a href="http://...">Abraham Lincoln</a></cite>

What exactly are the rules about when to include the \<cite> element? If the answer is "always", this will not work well with the way quotes were used in RFCs so far. This might require coordination with the RFCSTYLE RFC.

**Comment by hildjj** [comment]
This is a policy issue, not a format issue.

**Comment by reschke** [comment]
Looking at the vocabulary spec (https://greenbytes.de/tech/webdav/rfc7991.html#rfc.section.2.10.2) I see:

> 2.10.2. "cite" Attribute
> 
> The source of the citation. This must be a URI. If the "quotedFrom" attribute is given, this URI will be used by processing tools as the link for the text of that attribute.
>
> 2.10.3. "quotedFrom" Attribute
> 
> Name of person or document the text in this element is quoted from. A formatter should render this as visible text at the end of the quotation.

So the answer seems to be that the inclusion is triggered by the presence of "quotedFrom" -- I guess this works for me.

**Comment by reschke** [comment]
Implemented over in rfc2629.xslt: https://github.com/reschke/xml2rfc/commit/4ae5394780003c58d668ef1aefcd8e36d61eb854 - no issue here.
